### ISSUE TITLE
Работа с базой данных

### ISSUE THREAD

**Issue by mesherinovivan** [ArcLightSlavik/blog#1]
Добрый день!
Можешь рассказать, у тебя в блоге, есть файл database.py там происходить инициализация sqllite базы. Так же уровнем выше есть postgres.py, где используются настройки для postgres. Это просто недописанный переход на postgres или используются две базы?

**Comment by ArcLightSlavik** [comment]
@mesherinovivan Это переход. database.py ето конфигурация для sqlalchemy, а postgres.py для tortoise-orm.
